Traceback (most recent call last):
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2681, in version
    return self._version
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/bin/njob", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 769, in resolve
    if dist is None or (dist not in req and replace_conflicting):
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3133, in __contains__
    item = item.version
  File "/home/joao.pinto/new_git_repos/novacula/novacula-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2689, in version
    raise ValueError(msg, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file at path: /home/joao.pinto/new_git_repos/novacula/novacula.egg-info/PKG-INFO", novacula [unknown version] (/home/joao.pinto/new_git_repos/novacula))
